### ISSUE TITLE
Windows Compatability

### ISSUE THREAD

**Issue by Void2258** [ahertel/wholefoods-delivery-slot-finder#10]
This would be more generally accessible if it had a way to run on Windows as well as Mac.

**Comment by ahertel** [comment]
Thanks for the feedback :) I agree I wish this could work for everyone, but unfortunately I don't have the time to build an entirely new tool for all platforms in a universal language like python, or a Window specific language. I also don't own a Windows machine so I would have no way of testing it. However [@pcomputo](https://github.com/pcomputo/Whole-Foods-Delivery-Slot) already made a tool in Python that runs on all platforms. It might be helpful to you.

Despite the cons of AppleScript being platform specific, I think there are some pros, namely that it is easier to use. It requires no installation of another language(e.g python), or the editing of one's PATH, like @pcomputo's tool. Many people have messaged me saying that they appreciate that this runs right out to the box, because computer skills are not their strength.

Let me know if @pcomputo's tool works for you. [Auto Refresh Plus](https://chrome.google.com/webstore/detail/auto-refresh-plus/ohfjpkccecpdfkpmfocndhepolhljfhg?hl=en) is another option

Also, if you know how to build an equivalent tool for Windows, I'd be happy to post a link to it in the instructions of my tool.

**Comment by ghost** [comment]
https://github.com/kholia/OSX-KVM

**Comment by pcomputo** [comment]
Hi @ahertel! 
I just realized you have this amazing tool out there! Great work! :D 
We can totally get in touch if you'd like, to help each other out! 
Stay safe! :)
