### ISSUE TITLE
Compatibility with android 

### ISSUE THREAD

**Issue by allison1111** [ahertel/wholefoods-delivery-slot-finder#31]
Does this work on android's? If so can u send instructions?

**Comment by ahertel** [comment]
Sorry, this doesn't work for Android and I have no plans of adding compatibility with Android because this would require writing the entirely tool from scratch. I checked online and couldn't find any other similar tools that run on Android that I could refer you to. I suggest trying Prime Now on your Android phone at midnight in your time zone. Two nights in a row I got a slot at 12:03am by just manually refreshing.

Thanks for your understanding and wish you well.

**Comment by allison1111** [comment]
Thank you. I have heard about the midnight trick. Just tried obsessively
refreshing for 17 minutes starting at 1159 pm my time..
No luck :(

I recently signed up for prime. Is prime now something different?

Thank you
Allison

**Comment by ahertel** [comment]
@allison1111 the Prime Now is a separate app/service. it can be accessed at primenow.amazon.com or the [app on the Google Play Store](https://play.google.com/store/apps/details?id=com.amazon.now&hl=en_US)

I haven't had luck at midnight in the regular amazon.com /Amazon app grocery orders, which is why I created this tool. Let me know if you have better luck on Prime Now.
