### ISSUE TITLE
Page being sent backward.

### ISSUE THREAD

**Issue by gr8fly** [ahertel/wholefoods-delivery-slot-finder#41]
Hello,
Thank you so much for creating this! I am using it now for the first time and waiting for a slot to open. Unfortunately, I keep being sent out of the "checkout" area and back to the ordering page. Is there something on my end that I can do to fix this?

**Comment by ahertel** [comment]
Hi @gr8fly! Unfortunately this is just the nature of the beast. Please see the [disclaimer](https://github.com/ahertel/Amazon-Fresh-Whole-Foods-delivery-slot-finder#disclaimer-about-disappearing-slots). You can also checkout the discussion here (#13) where others have shared some musings, but at the end of the day this issue is on Amazon's end. The only way to get a slot is to keep trying to select the slots when they appear and to have the resilience to weed through all the "phantom slots"
Let me know if this helps. Thanks

**Comment by hwardshoes** [comment]
I feel like I need a tutorial on the getting started and downloaded the
app- planning to use with iPhone and am not seeing the same interface as
with desktop view on my pc. I know we need Mac so I’m just checking in to
see if there’s a guide to getting started with using this for iPhone!!
♥️♥️♥️♥️♥️♥️♥️♥️
